batch_size: 8192
ckpt_path: null
dataset_name: brics
distortion_loss_w: 0
downsample: 0.5
encoder_type: hash
exp_name: brics_ngp
gui: false
half2_opt: false
lr: 0.01
no_save_test: false
num_epochs: 1
perf: false
random_bg: false
ray_sampling_strategy: all_images
root_dir: /hdd_data/common/BRICS/taichi-seg/assets/objects/close_to_camera/image/
scale: 16.0
split: train
val_only: false
