batch_size: 8192
ckpt_path: null
dataset_name: ngp
distortion_loss_w: 0
downsample: 0.5
encoder_type: hash
exp_name: custom_ngp
gui: true
half2_opt: false
lr: 0.01
no_save_test: true
num_epochs: 1
perf: true
random_bg: false
ray_sampling_strategy: all_images
root_dir: /hdd_data/common/BRICS/instant_ngp_mod/data/nerf/fox/
scale: 16.0
split: train
val_only: false
